language: cpp
os: linux
dist: bionic
#sudo: false
compiler:
  - gcc

addons:
  apt:
    packages:
#      - libglew-dev
#      - freeglut3-dev
#      - libxi-dev
#      - libxmu-dev
#      - xserver-xorg-video-dummy
#      - xpra
#      - xorg-dev
#      - opencl-headers
#      - libgl1-mesa-dev
#      - libxcursor-dev
#      - libpulse-dev
#      - libxinerama-dev
#      - libxrandr-dev
#      - libxv-dev
#      - libasound2-dev
#      - libudev-dev
      - mesa-utils
      - libgl1-mesa-glx

#  libgl1-mesa-dev
#  libxcb-xkb-dev
#  xorg-dev libxcb-render-util0-dev
#  libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-xinerama0-dev
#
#before_install:
#  - sudo add-apt-repository -y ppa:oibaf/graphics-drivers

install:
#  - pip install --user ninja
  - pip install --user conan
  - conan user

script:
  - mkdir build
  - cd build
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan install .. --build imgui-sfml -s build_type=Debug
  - cmake .. -DENABLE_CONAN=ON -DENABLE_TESTS=ON -O0 -g
  - cmake --build . -- -j2
  - ctest -j2
  #  - conan install .. --build imgui-sfml -s build_type=Release
  #  - cmake .. -DENABLE_CONAN=ON -G "Ninja" -O3
  #  - ninja -j8
