language: cpp

install:
#  - pip install --user ninja
  - pip install --user conan
  - conan user

jobs:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode11.2
    - os: linux
      dist: bionic
      compiler: gcc

script:
  - mkdir build
  - cd build
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan install .. --build imgui-sfml -s build_type=Debug
  - cmake .. -DENABLE_CONAN=ON -DENABLE_TESTS=ON -O0 -g
  - cmake --build . -- -j2
  - ctest -j2
  #  - conan install .. --build imgui-sfml -s build_type=Release
  #  - cmake .. -DENABLE_CONAN=ON -G "Ninja" -O3
  #  - ninja -j8
