language: cpp
os: linux
dist: bionic
#sudo: false
compiler:
  - gcc

addons:
  apt:
    packages:
#      - libgl1-mesa-dev
#      - libgl1-mesa-glx
#      - mesa-utils
#      - xorg-dev
#      - libxcb-xkb-dev
#      - libxcb-render-util0-dev
#      - libxcb-icccm4-dev
#      - libxcb-image0-dev
#      - libxcb-keysyms1-dev
#      - libxcb-xinerama0-dev

#before_install:
#  - sudo add-apt-repository -y ppa:oibaf/graphics-drivers

install:
#  - pip install --user ninja
  - pip install --user conan
  - conan user

script:
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan profile list
#  - conan profile new default --detect
#  - conan profile update settings.compiler.libcxx=libstdc++11 default
#  - conan profile show default
  - mkdir build
  - cd build
  - conan install .. --build imgui-sfml -s build_type=Debug
  - conan profile list
  - conan profile show default
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - conan profile show default
    #  - cmake .. -DENABLE_CONAN=ON -DENABLE_TESTS=ON -O0 -DCMAKE_BUILD_TYPE=Debug
#  - cmake --build . -- -j2
#  - ctest -j2
  #  - conan install .. --build imgui-sfml -s build_type=Release
  #  - cmake .. -DENABLE_CONAN=ON -G "Ninja" -O3
  #  - ninja -j8
