language: cpp

install:
#  - pip install --user ninja
  - pip install --user conan
  - conan user
  - sudo apt install -y libgl1-mesa-dev xorg-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-xinerama0-dev

jobs:
  include:
#    - os: osx
#      compiler: clang
#      osx_image: xcode11.2
    - os: linux
      dist: bionic
      compiler: gcc
      sudo: true

script:
  - mkdir build
  - cd build
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan install .. --build imgui-sfml -s build_type=Debug
  - cmake .. -DENABLE_CONAN=ON -DENABLE_TESTS=ON -O0 -g
  - cmake --build . -- -j2
  - ctest -j2
  #  - conan install .. --build imgui-sfml -s build_type=Release
  #  - cmake .. -DENABLE_CONAN=ON -G "Ninja" -O3
  #  - ninja -j8
