language: cpp

install:
  - pip install --user ninja

jobs:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode11.2
    - os: linux
      dist: bionic
      compiler: gcc

script:
  - mkdir build
  - cd build
  - cmake ../ -DENABLE_TESTS=true
  - cmake --build . -- -j2
  - ctest -j2
  - ./starter_cpp
  - whereis ninja

# TODO install Ninja
#     - cmake ../ -DENABLE_TESTS=true -G"Ninja"
#     - ninja -j4